#! /bin /bash
a=20
b=30
if [ $a -eq $b ]
    then
            echo " $a is equal to $b"
    else
            echo " $a is not equal to $b"
fi        

#! /bin /bash
for i in A P P L E
do
echo "$i"
done



#! /bin /sh
echo "Enter your name"
read Name 
echo "Hello $Name"



#! /bin /sh
echo shell name $SHELL
echo home directory is $HOME
echo working directory is $PWD


#! /bin/sh
a=1
while [ $a -lt 11 ]
do
echo $a
a=` expr $a + 1 `
done

